# Generated by Django 4.1 on 2022-09-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
