# Generated by Django 4.1 on 2022-09-30 12:56

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_update_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='appendix',
            field=models.FileField(blank=True, null=True, upload_to=Projects.models.Project.file_location),
        ),
    ]
