# Generated by Django 4.1 on 2022-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion',
            field=models.IntegerField(default=0),
        ),
    ]
