# Generated by Django 4.1 on 2022-10-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_project_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion',
        ),
    ]
