# Generated by Django 4.1 on 2022-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_appendix'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.IntegerField(default=0),
        ),
    ]
