# Generated by Django 4.1 on 2022-10-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Logs.logcategory'),
        ),
    ]
